apiVersion: apps/v1
kind: Deployment
metadata:
  name: clover
  labels:
    app: clover
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clover
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: clover
    spec:
      containers:
      - name: clover
        image: registry.digitalocean.com/ceibo-registry/clover:1
        ports:
        - containerPort: 4000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: clover
  labels:
    app: clover
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 4000
  selector:
    app: clover
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: clover-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - weclover.com.ar
      secretName: clover-tls
  rules:
    - host: weclover.com.ar
      http:
        paths:
        - backend:
            serviceName: clover
            servicePort: 80
